name: My Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:
  workflow_run:
    workflows: ["My Workflow"]
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run test
        run: echo "Run test job automatically"
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
     - name: Run build
       run: echo "Run build job automatically"

  deploy:
    needs: build
    if: github.event_name == 'workflow_dispatch' || github.event_name == 'workflow_run'
    runs-on: ubuntu-latest
    steps:
     - name: Run Deploy
       run: echo "Run Deploy job automatically"
